Fix prisma seed command
The compiler options for `ts-node` are correctly set in the `ts-node` npm script, but `prisma seed` command isn't currently configured to use the `ts-node` script, it's using the `ts-node` binary, which doesn't have the proper compiler options, so running `npx prisma db seed` currently fails with the following error:

```
╰─ npx prisma db seed     

Running seed command `ts-node prisma/seed.ts` ...

An error occured while running the seed command:
/Users/mplis/workspace/graphql-nextjs/prisma/seed.ts:1
import { PrismaClient } from '@prisma/client';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module.m._compile (/Users/mplis/workspace/graphql-nextjs/node_modules/ts-node/src/index.ts:1310:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/mplis/workspace/graphql-nextjs/node_modules/ts-node/src/index.ts:1313:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at main (/Users/mplis/workspace/graphql-nextjs/node_modules/ts-node/src/bin.ts:331:12)
    at Object.<anonymous> (/Users/mplis/workspace/graphql-nextjs/node_modules/ts-node/src/bin.ts:482:3)
```